# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  options,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/483d3f17-4d42-489d-9f3b-27a90c964a4e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/66E6-B623";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/a7add27a-2a35-4483-ba66-cf7edb0f2ffa";}];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.nitrokey = {
    enable = true;
  };

  hardware.pulseaudio = {
    enable = false;
    # NixOS allows either a lightweight build (default) or full build of PulseAudio to be installed.
    # Only the full build has Bluetooth support, so it must be selected here.
    package = pkgs.pulseaudioFull;
    extraModules = [];
    extraConfig = ''
      load-module module-udev-detect ignore_dB=1
    '';
  };

  hardware.bluetooth.enable = true;
  hardware.bluetooth.settings = {
    General = {Enable = "Source,Sink,Media,Socket";};
  };
}
