# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/221c7c83-eabe-444e-9507-b97a6b023823";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5ee76524-c36f-40aa-91d1-f9496785283e".device = "/dev/disk/by-uuid/5ee76524-c36f-40aa-91d1-f9496785283e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/08BA-F47A";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/43f48350-1c39-48ca-bd92-6941f136fbea";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nitrokey = {
    enable = true;
  };

  hardware.pulseaudio = {
    enable = false;
    # NixOS allows either a lightweight build (default) or full build of PulseAudio to be installed.
    # Only the full build has Bluetooth support, so it must be selected here.
    package = pkgs.pulseaudioFull;
    extraModules = [];
    extraConfig = ''
      load-module module-udev-detect ignore_dB=1
    '';
  };

  hardware.bluetooth.enable = true;
  hardware.bluetooth.settings = {
    General = {Enable = "Source,Sink,Media,Socket";};
  };
}
