# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2db828d2-04fa-4d86-987c-f55a574bf193";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/18C7-421C";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4954e002-ec10-45c6-8089-a7472711ec5c";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/cfbed17e-5bba-43c7-b551-ea4b80824f61"; }];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # hardware.opengl.driSupport32Bit = true;
  
  # nvidia.enable = true;
  # hardware.cpu.intel.updateMicrocode = true;

  hardware.bluetooth.enable = true;

  hardware.nitrokey = {
    enable = true;
    # group = "wheel";
  };

  hardware.pulseaudio = {
    enable = true;
    # NixOS allows either a lightweight build (default) or full build of PulseAudio to be installed.
    # Only the full build has Bluetooth support, so it must be selected here.
    package = pkgs.pulseaudioFull;
    extraModules = [ pkgs.pulseaudio-modules-bt ];
    extraConfig = ''
    load-module module-udev-detect ignore_dB=1
    '';
  };

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;

}
