# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/246279f8-9414-4b52-b18c-8d603ee18deb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e7e0cf9a-e269-401f-a22c-1794f9901e60".device = "/dev/disk/by-uuid/e7e0cf9a-e269-401f-a22c-1794f9901e60";

  swapDevices = [
    {device = "/dev/disk/by-uuid/c6f83e59-d846-4620-99eb-f47ce0664989";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp164s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nitrokey = {
    enable = true;
  };

  hardware.pulseaudio = {
    enable = false;
    # NixOS allows either a lightweight build (default) or full build of PulseAudio to be installed.
    # Only the full build has Bluetooth support, so it must be selected here.
    package = pkgs.pulseaudioFull;
    extraModules = [];
    extraConfig = ''
      load-module module-udev-detect ignore_dB=1
    '';
  };

  hardware.bluetooth.enable = true;
  hardware.bluetooth.settings = {
    General = {Enable = "Source,Sink,Media,Socket";};
  };
}
