# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.extraModulePackages = [];
  boot.kernelModules = [
    "kvm-intel"
  ];

  boot.extraModprobeConfig = ''
    options snd_sof_intel_hda_generic hda_model=alc287-yoga9-bass-spk-pin
  '';

  hardware.firmware = with pkgs; [sof-firmware];
  hardware.enableAllFirmware = true;

  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.latest;
  };

  services.xserver.videoDrivers = ["nvidia"];
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ac104196-8b91-4f61-bec1-03ef5160a3a6";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-63fd4ea1-7ec5-481f-b865-ee8252f07b5f".device = "/dev/disk/by-uuid/63fd4ea1-7ec5-481f-b865-ee8252f07b5f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/160F-E74A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  hardware.bluetooth.enable = true;
  hardware.bluetooth.settings = {
    General = {Enable = "Source,Sink,Media,Socket";};
  };

  hardware.nitrokey = {
    enable = true;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
